"""
Admin registrations are a convenience for the CTO during the build, not the
product surface. The audit log is deliberately read-only here: it is
append-only by design and must not be editable from any screen.
"""
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin

from .models import AuditEntry, Permission, Role, RolePermission, User, UserRole


class RolePermissionInline(admin.TabularInline):
    model = RolePermission
    extra = 0


class UserRoleInline(admin.TabularInline):
    model = UserRole
    fk_name = "user"
    extra = 0


@admin.register(User)
class UserAdmin(DjangoUserAdmin):
    list_display = ("email", "first_name", "last_name", "is_active", "must_reset_password")
    search_fields = ("email", "first_name", "last_name")
    inlines = [UserRoleInline]
    fieldsets = DjangoUserAdmin.fieldsets + (
        ("A1 access", {"fields": ("must_reset_password", "failed_login_attempts", "locked_until")}),
    )


@admin.register(Permission)
class PermissionAdmin(admin.ModelAdmin):
    list_display = ("code", "module", "description")
    list_filter = ("module",)
    search_fields = ("code", "description")

    def has_add_permission(self, request):
        # The permission list is the frozen contract, generated by
        # `seed_permissions` from the registry — never typed in by hand.
        return False


@admin.register(Role)
class RoleAdmin(admin.ModelAdmin):
    list_display = ("name", "is_system")
    inlines = [RolePermissionInline]


@admin.register(AuditEntry)
class AuditEntryAdmin(admin.ModelAdmin):
    list_display = ("created_at", "actor", "action", "target_type", "target_id")
    list_filter = ("action",)
    search_fields = ("action", "target_type", "target_id", "reason")

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False
