# Generated by Django 5.2.6 on 2026-09-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_options_task_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [models.OrderBy(models.F('completed_at'), nulls_first=True), models.OrderBy(models.F('due_date'), nulls_last=True), 'id']},
        ),
    ]
