# Generated by Django 5.2.6 on 2026-09-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='Metres, bags, lengths — whatever it is counted in.', max_length=30)),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.requisition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
