# Generated by Django 5.2.6 on 2026-09-03 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('device_timestamp', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('location_unavailable', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('in', 'Clock in'), ('out', 'Clock out')], max_length=8)),
                ('recorded_by', models.ForeignKey(blank=True, help_text="Set when a supervisor records on the employee's behalf.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('amend_time', 'Amend time'), ('void', 'Void event')], default='amend_time', max_length=20)),
                ('original_timestamp', models.DateTimeField()),
                ('corrected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='config.correctionreason')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='hr.attendanceevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='hr.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('still_clocked_in', models.BooleanField(default=False)),
                ('correction_count', models.PositiveIntegerField(default=0)),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='hr.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__staff_id'],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['employee', 'device_timestamp'], name='hr_attendan_employe_9f33b6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['date', 'employee'], name='hr_attendan_date_ab4495_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceday',
            unique_together={('employee', 'date')},
        ),
    ]
