# Generated by Django 5.2.6 on 2026-09-07 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('description', models.CharField(help_text='What this code is for, e.g. Main office', max_length=120)),
                ('location_name', models.CharField(help_text='Where it is posted', max_length=120)),
                ('expires_at', models.DateTimeField(help_text='After this moment the code stops working and HR prints a new one.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr.attendancecode'),
        ),
        migrations.AddIndex(
            model_name='attendancecode',
            index=models.Index(fields=['token'], name='hr_attendan_token_27fd4f_idx'),
        ),
    ]
