# Generated by Django 4.0.8 on 2023-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing')], max_length=50, null=True),
        ),
    ]
