# Generated by Django 4.0.8 on 2023-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
