# Generated by Django 4.0.8 on 2023-09-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_calllog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
