# Generated by Django 3.1.14 on 2023-10-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20231002_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
