# Generated by Django 5.2.6 on 2026-09-13 06:35

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=accounts.models.profile_photo_path)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=280, verbose_name='About me')),
                ('personal_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Home address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, verbose_name='Name')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=60, verbose_name='Relationship')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('x_url', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
