# Generated by Django 5.2.6 on 2026-09-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_birthday',
            field=models.BooleanField(default=True, help_text='Colleagues see the day and month on the dashboard. Never the year.', verbose_name='Show my birthday to colleagues'),
        ),
    ]
