"""
A ticket says when the work is expected to happen, not only when it was
handed over.

`assigned_at` records the moment a supervisor pressed the button. These two
are what the technician is being asked for, and what anybody planning around
them needs to see. Both optional: plenty of tickets are "today, when you get
a minute".
"""
# Generated by Django 5.2.6 on 2026-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
