# Generated by Django 5.2.6 on 2026-09-03 00:20

import approvals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('device_timestamp', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('location_unavailable', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='config.servicetype')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-device_timestamp'],
            },
            bases=(approvals.models.ApprovalTrailMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssessmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('image', models.ImageField(upload_to='assessments/')),
                ('label', models.CharField(max_length=150)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fieldjobs.assessment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FieldJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='crm.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='projects.project')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='config.servicetype')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='crm.site')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='crm.ticket')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('device_timestamp', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('location_unavailable', models.BooleanField(default=False)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
                ('field_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='fieldjobs.fieldjob')),
            ],
            options={
                'ordering': ['device_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='field_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='fieldjobs.fieldjob'),
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=300)),
                ('respondent', models.CharField(max_length=20)),
                ('value_text', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fieldjobs.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='config.assessmentquestion')),
            ],
            options={
                'ordering': ['question__order', 'id'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='fieldjob',
            index=models.Index(fields=['assigned_to', 'scheduled_for'], name='fieldjobs_f_assigne_4ec4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldjob',
            index=models.Index(fields=['job_ref'], name='fieldjobs_f_job_ref_8b6076_idx'),
        ),
    ]
