# Generated by Django 5.2.6 on 2026-09-07 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldjobs', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldJobCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_job_assignments', to='hr.employee')),
                ('field_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='fieldjobs.fieldjob')),
            ],
            options={
                'ordering': ['employee__staff_id'],
                'unique_together': {('field_job', 'employee')},
            },
        ),
    ]
