# Generated by Django 5.2.6 on 2026-09-29 15:47

import django.db.models.deletion
"""
A field job records who scheduled it.

More than one person in the office can put work on a technician's phone, so
"the office sent you" was not an answer to why somebody was driving to Ganta
on a Friday. Jobs recorded before this was asked for keep an honest blank
rather than being attributed to whoever ran the migration.
"""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldjobs', '0002_fieldjobcrew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldjob',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_jobs_scheduled', to=settings.AUTH_USER_MODEL),
        ),
    ]
