# Generated by Django 3.1.14 on 2023-08-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230808_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='staff_id',
        ),
    ]
